# .github/workflows/metrics.yml

name: Example Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS }}
          base: header, metadata
          config_output: Hi! I am Kishgi. Welcome
      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, 
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS}}
