name: Update Thirukkural Daily

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:     

permissions:
  contents: write
  
jobs:
  update-kural:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requests
        run: pip install requests

      - name: Run the Update Script
        run: python update_kural.py

      - name: Commit Changes
        run: |
          git config --global user.name 'kishgi'
          git config --global user.email 'kishgi1234@gmail.com'
          git add README.md
          git commit -m "📝 Update Thirukkural of the Day" || echo "No changes to commit"
          git push
